name: Lint Markdown files

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  markdown_lint:
    name: Check Markdown files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Markdown Lint
        uses: ruzickap/action-my-markdown-linter@v1
        with:
          config_file: .markdownlint.yml
